/** Live, controlled, loopback-only framework matrix. No target websites. */
import {createServer} from 'node:http';import {chromium} from 'playwright';import puppeteer from 'puppeteer-core';import {Builder,By} from 'selenium-webdriver';import chrome from 'selenium-webdriver/chrome.js';import {scoreSignals} from '../src/detect.js';import {build} from 'esbuild';import {resolve} from 'node:path';import {writeFile} from 'node:fs/promises';
const chromePath=process.env.CHROME_PATH || '/usr/bin/google-chrome';
const botd=await build({entryPoints:[resolve('node_modules/@fingerprintjs/botd/dist/botd.esm.js')],bundle:true,format:'iife',globalName:'BotD',write:false});const bs=await build({entryPoints:[resolve('node_modules/bot-signal/dist/browser.js')],bundle:true,format:'iife',globalName:'BotSignal',write:false});const server=createServer((req,res)=>{if(req.url==='/botd.js'){res.setHeader('Content-Type','text/javascript');res.end(botd.outputFiles[0].text);return}if(req.url==='/bs.js'){res.setHeader('Content-Type','text/javascript');res.end(bs.outputFiles[0].text);return}res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Local test</title><button>OK</button>')});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/`;const js=`return {navigator:{webdriver:navigator.webdriver,webdriverOwnProperty:Object.prototype.hasOwnProperty.call(navigator,"webdriver"),userAgent:navigator.userAgent},window:{globalNames:Object.getOwnPropertyNames(window).filter(x=>/^(__playwright|__pw_|__puppeteer|_selenium|__webdriver|cdc_[a-zA-Z0-9]{10,}_(?:Array|JSON|Object|Promise|Proxy|Symbol|Window)$)/i.test(x))}}`;
const rows=[];const compare=async (snap,evalFn)=>({ours:scoreSignals(snap),botd:await evalFn('return BotD.load().then(x=>x.detect())'),botSignal:await evalFn('return BotSignal.detectInstantClient(window).isLegitClient')});
try{
 for(const masked of [false,true]){
  let b=await chromium.launch({headless:false,executablePath:chromePath,args:['--no-sandbox']});let c=await b.newContext(masked?{userAgent:'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}:{});if(masked)await c.addInitScript('Object.defineProperty(navigator,"webdriver",{get:()=>undefined})');let p=await c.newPage();await p.goto(url);await p.addScriptTag({url:url+'botd.js'});await p.addScriptTag({url:url+'bs.js'});let snap=await p.evaluate(new Function(js));rows.push({framework:'Playwright',masked,result:await compare(snap,x=>p.evaluate(new Function(x)))});await b.close();
 }
 for(const masked of [false,true]){
  let b=await puppeteer.launch({headless:false,executablePath:chromePath,args:['--no-sandbox']});let p=await b.newPage();if(masked){await p.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36');await p.evaluateOnNewDocument('Object.defineProperty(navigator,"webdriver",{get:()=>undefined})')};await p.goto(url);await p.addScriptTag({url:url+'botd.js'});await p.addScriptTag({url:url+'bs.js'});let snap=await p.evaluate(new Function(js));rows.push({framework:'Puppeteer',masked,result:await compare(snap,x=>p.evaluate(new Function(x)))});await b.close();
 }
 for(const masked of [false,true]){
  let opts=new chrome.Options().setChromeBinaryPath(chromePath).addArguments('--no-sandbox');if(masked){opts.addArguments('--disable-blink-features=AutomationControlled');opts.addArguments('--user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36')}let d=await new Builder().forBrowser('chrome').setChromeOptions(opts).build();try{await d.get(url);await d.executeScript(`let a=document.createElement('script');a.src='${url}botd.js';document.head.appendChild(a);let b=document.createElement('script');b.src='${url}bs.js';document.head.appendChild(b);`);await d.wait(async()=>d.executeScript('return !!window.BotD && !!window.BotSignal'),5000);let snap=await d.executeScript(js);rows.push({framework:'Selenium',masked,result:await compare(snap,x=>d.executeAsyncScript(`const cb=arguments[arguments.length-1]; Promise.resolve((new Function(${JSON.stringify(x)}))()).then(cb).catch(e=>cb({error:String(e)}))`))});}finally{await d.quit()}
 }
}finally{server.close()};const out=rows.map(x=>({framework:x.framework,masked:x.masked,class:x.result.ours.classification,signals:x.result.ours.signals.map(y=>y.id),botd:x.result.botd,botSignal:x.result.botSignal}));await writeFile(resolve('bench/framework-headed-results.json'),JSON.stringify({date:new Date().toISOString(),environment:'Google Chrome local loopback, headed Playwright/Puppeteer/Selenium under Xvfb',results:out},null,2));console.log(JSON.stringify(out,null,2));
